#!/usr/bin/env python3
"""Generate a Discovery Service Ed25519 DID keypair.

Run this once to generate a stable identity for the Discovery Service.
Paste the printed lines into .env.local.

Usage:
    python scripts/generate_discovery_did.py

Requires:
    pip install cryptography  (already in discovery service deps)
    -- OR --
    run from within the discovery service venv / Docker build context

Output (example):
    DISCOVERY_PRIVATE_KEY_HEX=3a7f...
    JWT_ISSUER_DID=did:key:z6Mk...
    JWT_ISSUER_KEY_ID=did:key:z6Mk...#z6Mk...
"""
from __future__ import annotations

import sys
from pathlib import Path

# Allow running from repo root without installing the package
_REPO_ROOT = Path(__file__).parent.parent
_COMMON_SRC = _REPO_ROOT / "libs" / "common" / "src"
if str(_COMMON_SRC) not in sys.path:
    sys.path.insert(0, str(_COMMON_SRC))

from common.crypto.did_key import generate_did_key


def main() -> None:
    kp = generate_did_key()
    private_hex = kp.private_key_bytes.hex()

    print("# ----------------------------------------------------------------")
    print("# Discovery Service DID identity — generated by generate_discovery_did.py")
    print("# Add these lines to .env.local")
    print("# KEEP PRIVATE_KEY_HEX SECRET — treat like a password")
    print("# ----------------------------------------------------------------")
    print(f"DISCOVERY_PRIVATE_KEY_HEX={private_hex}")
    print(f"JWT_ISSUER_DID={kp.did}")
    print(f"JWT_ISSUER_KEY_ID={kp.verification_method_id}")
    print("VERIFY_ISSUER_ON_CHAIN=true")
    print()
    print("#  Then rebuild discovery:")
    print("#    docker compose --env-file .env.local up -d --build discovery")


if __name__ == "__main__":
    main()
